local M = {}

function M.get(theme, colors, opts)
  -- stylua: ignore
  return {
    Added             = { fg   = colors.green        },
    Removed           = { fg   = colors.red          },
    Changed           = { fg   = colors.yellow       },
    MatchWord         = { fg   = colors.white,       bg = colors.grey     },
    Pmenu             = { bg   = colors.one_bg       },
    PmenuSbar         = { bg   = colors.one_bg       },
    PmenuSel          = { fg   = colors.black,       bg = colors.pmenu_bg },
    PmenuThumb        = { bg   = colors.grey         },
    MatchParen        = { link = "MatchWord"         },
    Comment           = { fg   = colors.light_grey   },
    CursorLineNr      = { fg   = colors.white        },
    LineNr            = { fg   = colors.grey         },
    FloatBorder       = { fg   = colors.blue         },
    FloatTitle        = { fg   = colors.white,       bg = colors.grey     },
    NormalFloat       = { bg   = colors.darker_black },
    NvimInternalError = { fg   = colors.red          },
    WinSeparator      = { fg   = colors.line         },
    Normal            = { fg   = theme.base05,       bg = theme.base00    },
    DevIconDefault    = { fg   = colors.red          },
    Debug             = { fg   = theme.base08        },
    Directory         = { fg   = theme.base0D        },
    Error             = { fg   = theme.base00,       bg = theme.base08    },
    ErrorMsg          = { fg   = theme.base08,       bg = theme.base00    },
    Exception         = { fg   = theme.base08        },
    FoldColumn        = { bg   = "none"              },
    Folded            = { fg   = colors.light_grey,  bg = colors.black2   },
    IncSearch         = { fg   = "#000000",          bg = theme.base09    },
    Macro             = { fg   = theme.base08        },
    ModeMsg           = { fg   = theme.base0B        },
    MoreMsg           = { fg   = theme.base0B        },
    Question          = { fg   = theme.base0D        },
    Search            = { fg   = "#000000",          bg = theme.base0A    },
    Substitute        = { fg   = theme.base01,       bg = theme.base0A    },
    SpecialKey        = { fg   = theme.base03        },
    TooLong           = { fg   = theme.base08        },
    Visual            = { bg   = theme.base02        },
    VisualNOS         = { fg   = theme.base08        },
    WarningMsg        = { fg   = theme.base08        },
    WildMenu          = { fg   = theme.base08,       bg = theme.base0A    },
    Title             = { fg   = theme.base0D        },
    Conceal           = { bg   = "NONE"              },
    Cursor            = { fg   = theme.base00,       bg = theme.base05    },
    NonText           = { fg   = theme.base03        },
    SignColumn        = { fg   = theme.base03        },
    ColorColumn       = { bg   = colors.black2       },
    CursorColumn      = { bg   = theme.base01        },
    CursorLine        = { bg   = colors.black2       },
    QuickFixLine      = { bg   = theme.base01        },
    healthSuccess     = { fg   = colors.black,       bg = colors.green    },
    WinBar   = { bg = "NONE" },
    WinBarNC = { bg = "NONE" },
  }
end

return M
