-- From Lazyvim with some small tweaks such as some changed colors,
-- some components placed slightly differenly.

return {
    "nvim-lualine/lualine.nvim",
    enabled = true,
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    event = "VeryLazy",
    init = function()
      vim.g.lualine_laststatus = vim.o.laststatus
      if vim.fn.argc(-1) > 0 then
        -- set an empty statusline till lualine loads
        vim.o.statusline = " "
      else
        -- hide the statusline on the starter page
        vim.o.laststatus = 0
      end

    end,
    opts = function()
      local lualine_require = require("lualine_require")
      lualine_require.require = require

      vim.o.laststatus = vim.g.lualine_laststatus

      -- Make custom theme from autogenerated one.
      local auto = require("lualine.themes.auto")
      local custom = vim.deepcopy(auto)

      -- lualine_a_normal
      -- Override mode backgrounds
      custom.normal.a.bg = "#598cbf"
      custom.normal.a.fg = "#000000"
      custom.insert.a.bg = "#99C794"
      -- custom.insert.a.bg  = ""
      -- custom.visual.a.bg  = ""
      -- custom.replace.a.bg = ""
      -- custom.command.a.bg = ""

      -- (Keep Base46 foreground if you want)
      -- custom.normal.a.fg = auto.normal.a.fg
      --
      -- b: '#1b2c34'
      -- c: '#22333d'

      local off_white = "#d4d4d4"

      local opts = {
        options = {
          -- Can be set to auto or nil.
          theme = custom,
          globalstatus = vim.o.laststatus == 3,
          disabled_filetypes = { statusline =
            { "dashboard", "alpha", "ministarter", "snacks_dashboard" }
          },
          -- Get rid off '' and ''.
          component_separators = { left = '', right = ' '},
        },
        sections = {
          lualine_a = {
            { "mode" },
          },
          lualine_b = {
            { "branch", color = { fg = off_white } },
            "diff", -- Git diff status
          },
          -- lualine_b = { 'branch', 'diff', 'diagnostics' },  -- Default
          lualine_c = {
            "diagnostics",
            { 'filename', color = { fg = off_white } },
          },

	          lualine_x = {
	            -- stylua: ignore
	            { -- normal-mode count prefix (e.g. 5 in 5dw)
	              function() return tostring(vim.v.count) end,
	              cond = function() return vim.v.count > 0 end,
	              color = function() return { fg = Snacks.util.color("Statement") } end,
	            },
	            -- stylua: ignore
	            {  -- command: showcmd
	              function()
	                return require("noice").api.status.command.get()
	              end,
	              cond = function()
	                return package.loaded["noice"] and require("noice").api.status.command.has()
	              end,
	              color = function() return { fg = Snacks.util.color("Statement") } end,
	            },
            -- stylua: ignore
            { -- mode: showmode (@recording messages)
            function() return require("noice").api.status.mode.get() end,
              cond = function()
                return package.loaded["noice"] and require("noice").api.status.mode.has()
              end,
              color = function() return { fg = Snacks.util.color("Constant") } end,
            },
            Snacks.profiler.status(),
            -- stylua: ignore
            { -- Show number of updates available.
              require("lazy.status").updates,
              cond = require("lazy.status").has_updates,
              color = function() return { fg = Snacks.util.color("Special") } end,
            },
            { "encoding", color = { fg = off_white } },
            { "fileformat", color = { fg = off_white } },
            { "filetype", color = { fg = off_white } },
          },

          lualine_y = {
            { "progress", separator = " ", padding = { left = 1, right = 0 } },
            { "location", padding = { left = 0, right = 1 } },
          },
          lualine_z = {
            {
            function() return " " .. os.date("%R") end,
              color = { fg = '#000000' }
            }
          },
        },
        extensions = { "lazy" },
      }
      return opts
    end,
  }

