
-- UI related plugins.

if vim.g.vscode then
  return {}
end

return {

-- Bufferline. From LazyVim.
  {
    'akinsho/bufferline.nvim',
    enabled = true,
    version = "*",
    dependencies = 'nvim-tree/nvim-web-devicons',
    event = "VeryLazy",
    keys = {
      { "<leader>bp", "<Cmd>BufferLineTogglePin<CR>", desc = "Toggle Pin" },
      { "<leader>bP", "<Cmd>BufferLineGroupClose ungrouped<CR>", desc = "Delete Non-Pinned Buffers" },
      { "<leader>br", "<Cmd>BufferLineCloseRight<CR>", desc = "Delete Buffers to the Right" },
      { "<leader>bl", "<Cmd>BufferLineCloseLeft<CR>", desc = "Delete Buffers to the Left" },
      { "<S-h>", "<cmd>BufferLineCyclePrev<cr>", desc = "Prev Buffer" },
      { "<S-l>", "<cmd>BufferLineCycleNext<cr>", desc = "Next Buffer" },
      { "[b", "<cmd>BufferLineCyclePrev<cr>", desc = "Prev Buffer" },
      { "]b", "<cmd>BufferLineCycleNext<cr>", desc = "Next Buffer" },
      { "[B", "<cmd>BufferLineMovePrev<cr>", desc = "Move buffer prev" },
      { "]B", "<cmd>BufferLineMoveNext<cr>", desc = "Move buffer next" },
    },
    opts = {

      options = {
        -- stylua: ignore
        close_command = function(n) Snacks.bufdelete(n) end,
        always_show_bufferline = false,
        offsets = {
          {
            filetype = "neo-tree",
            text = "Neo-tree",
            highlight = "Directory",
            text_align = "left",
          },
          {
            filetype = "snacks_layout_box",
          },
        },
      }
    },

    config = function(_, opts)
      require("bufferline").setup(opts)
      -- Fix bufferline when restoring a session
      vim.api.nvim_create_autocmd({ "BufAdd", "BufDelete" }, {
        callback = function()
          vim.schedule(function()
            pcall(nvim_bufferline)
          end)
        end,
      })
    end,

  },

-- Lualine. From Lazyvim with some small tweaks such as some changed colors,
-- some components placed slightly differenly.
  {
    "nvim-lualine/lualine.nvim",
    enabled = true,
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    event = "VeryLazy",
    init = function()
      vim.g.lualine_laststatus = vim.o.laststatus
      if vim.fn.argc(-1) > 0 then
        -- set an empty statusline till lualine loads
        vim.o.statusline = " "
      else
        -- hide the statusline on the starter page
        vim.o.laststatus = 0
      end

    end,
    opts = function()
      local lualine_require = require("lualine_require")
      lualine_require.require = require

      vim.o.laststatus = vim.g.lualine_laststatus

      -- Make custom theme from autogenerated one.
      local auto = require("lualine.themes.auto")
      local custom = vim.deepcopy(auto)

      -- lualine_a_normal
      -- Override mode backgrounds
      custom.normal.a.bg = "#598cbf"
      custom.normal.a.fg = "#000000"
      custom.insert.a.bg = "#99C794"
      -- custom.insert.a.bg  = ""
      -- custom.visual.a.bg  = ""
      -- custom.replace.a.bg = ""
      -- custom.command.a.bg = ""

      -- (Keep Base46 foreground if you want)
      -- custom.normal.a.fg = auto.normal.a.fg
      --
      -- b: '#1b2c34'
      -- c: '#22333d'

      local off_white = "#d4d4d4"

      local opts = {
        options = {
          -- Can be set to auto or nil.
          theme = custom,
          globalstatus = vim.o.laststatus == 3,
          disabled_filetypes = { statusline =
            { "dashboard", "alpha", "ministarter", "snacks_dashboard" }
          },
          -- Get rid off '' and ''.
          component_separators = { left = '', right = ' '},
        },
        sections = {
          lualine_a = {
            { "mode" },
          },
          lualine_b = {
            { "branch", color = { fg = off_white } },
            "diff", -- Git diff status
          },
          -- lualine_b = { 'branch', 'diff', 'diagnostics' },  -- Default
          lualine_c = {
            "diagnostics",
            { 'filename', color = { fg = off_white } },
          },

          lualine_x = {
            -- stylua: ignore
            {  -- command: showcmd
            function() return require("noice").api.status.command.get() end,
              cond = function()
                return package.loaded["noice"] and require("noice").api.status.command.has()
              end,
              color = function() return { fg = Snacks.util.color("Statement") } end,
            },
            -- stylua: ignore
            { -- mode: showmode (@recording messages)
            function() return require("noice").api.status.mode.get() end,
              cond = function()
                return package.loaded["noice"] and require("noice").api.status.mode.has()
              end,
              color = function() return { fg = Snacks.util.color("Constant") } end,
            },
            Snacks.profiler.status(),
            -- stylua: ignore
            { -- Show number of updates available.
              require("lazy.status").updates,
              cond = require("lazy.status").has_updates,
              color = function() return { fg = Snacks.util.color("Special") } end,
            },
            { "encoding", color = { fg = off_white } },
            { "fileformat", color = { fg = off_white } },
            { "filetype", color = { fg = off_white } },
          },

          lualine_y = {
            { "progress", separator = " ", padding = { left = 1, right = 0 } },
            { "location", padding = { left = 0, right = 1 } },
          },
          lualine_z = {
            {
            function() return " " .. os.date("%R") end,
              color = { fg = '#000000' }
            }
          },
        },
        extensions = { "lazy" },
      }
      return opts
    end,
  },

  -- From LazyVim with some commented changes.
  {
    "nvim-neo-tree/neo-tree.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "MunifTanjim/nui.nvim",
      "nvim-tree/nvim-web-devicons", -- optional, but recommended
    },
    lazy = false,   -- neo-tree will lazily load itself
    cmd = "Neotree",
    enabled = true,
    keys = {
      {
        "<leader>e", function()
          local buf = vim.api.nvim_get_current_buf()
          -- Use root definition from Mini.misc instead of LazyVim.
          local root = require("mini.misc").find_root(buf) or vim.loop.cwd()
          require("neo-tree.command").execute({ toggle = true, dir = root })
        end, desc = "Explorer NeoTree (root)",

        -- local root = require("mini.misc").find_root(buf)
      },
      -- Lazyvim default
      -- { "<leader>e", "<leader>fe", desc = "Explorer NeoTree (Root Dir)", remap = true },
      {
        "<leader>E", function()
          require("neo-tree.command").execute({ toggle = true, dir = vim.uv.cwd() })
        end,
        desc = "Explorer NeoTree (cwd)",
      },
      { "<leader>fe", "<leader>e", desc = "Explorer NeoTree (root)", remap = true },
      { "<leader>fE", "<leader>E", desc = "Explorer NeoTree (cwd)", remap = true },
      {
        "<leader>ge", function()
          require("neo-tree.command").execute({ source = "git_status", toggle = true })
        end,
        desc = "Git Explorer",
      },
      {
        "<leader>be", function()
          require("neo-tree.command").execute({ source = "buffers", toggle = true })
        end,
        desc = "Buffer Explorer",
      },
    },
    deactivate = function()
      vim.cmd([[Neotree close]])
    end,
    -- init = function()
    -- FIX: use `autocmd` for lazy-loading neo-tree instead of directly requiring it,
    -- because `cwd` is not set up properly.
    --   vim.api.nvim_create_autocmd("BufEnter", {
    --     group = vim.api.nvim_create_augroup("Neotree_start_directory", { clear = true }),
    --     desc = "Start Neo-tree with directory",
    --     once = true,
    --     callback = function()
    --       if package.loaded["neo-tree"] then
    --         return
    --       else
    --         local stats = vim.uv.fs_stat(vim.fn.argv(0))
    --         if stats and stats.type == "directory" then
    --           require("neo-tree")
    --         end
    --       end
    --     end,
    --   })
    -- end,
    opts = {
      sources = { "filesystem", "buffers", "git_status" },
      source_selector = {
        winbar = true,
        content_layout = "center",
      },
      open_files_do_not_replace_types = { "terminal", "Trouble", "trouble", "qf", "Outline" },
      filesystem = {
        bind_to_cwd = false,
        follow_current_file = {
          enabled = true,
          leave_dirs_open = false, -- Optional: Determines whether to close other directories when following
        },
        -- filtered_items = {
        --   hide_dotfiles = false, -- Adjust other filtering options as needed
        --   hide_by_name = { ".git", "node_modules" }, -- Example filters
        -- },
        use_libuv_file_watcher = true,
        search_command = "fd --follow", -- Follow symlinks while searching
        hijack_netrw_behavior = "open_default", -- Relevant for symlink resolution
      },

      window = {
        mappings = {
          -- Neovim default search. Jump to name without doing resursive search.
          ["/"] = { function()
            vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("/", true, false, true), "n", true)
          end },
          -- This is recursive search mapped by default to /.
          ["F"] = "fuzzy_finder",
          ["l"] = "open",
          ["h"] = "close_node",
          ["Y"] = {
            function(state)
              local node = state.tree:get_node()
              local path = node:get_id()
              vim.fn.setreg("+", path, "c")
            end,
            desc = "Copy Path to Clipboard",
          },
          -- ["O"] = {
          --   function(state)
          --     require("lazy.util").open(state.tree:get_node().path, { system = true })
          --   end,
          --   desc = "Open with System Application",
          -- },
          ["M-p"] = { "toggle_preview", config = { use_float = false } },
        },
      },
      default_component_configs = {
        indent = {
          with_expanders = true, -- if nil and file nesting is enabled, will enable expanders
          expander_collapsed = "",
          expander_expanded = "",
          expander_highlight = "NeoTreeExpander",
          symlink_target = { enabled = true },
        },
        git_status = {
          symbols = {
            -- unstaged = "󰄱",
            -- staged = "󰱒",
            -- added     = "✚",
            -- deleted   = "✖",
            -- modified  = "",
            -- renamed   = "󰁕",
            -- -- Status type
            -- untracked = "",
            -- ignored   = "",
            -- unstaged  = "󰄱",
            -- staged    = "",
            -- conflict  = "",
          },
        },
      },
    },

    config = function(_, opts)
      local function on_move(data)
        Snacks.rename.on_rename_file(data.source, data.destination)
      end

      local events = require("neo-tree.events")
      opts.event_handlers = opts.event_handlers or {}
      vim.list_extend(opts.event_handlers, {
        { event = events.FILE_MOVED, handler = on_move },
        { event = events.FILE_RENAMED, handler = on_move },
      })

      require("neo-tree").setup(opts)
      local darker_black = "#122027"
      vim.api.nvim_set_hl(0, "NeoTreeTabInactive", { fg = "#5f6f78", bg = darker_black })
      vim.api.nvim_set_hl(0, "NeoTreeTabSeparatorInactive", { fg = darker_black, bg = darker_black })
      vim.api.nvim_set_hl(0, "NeoTreeGitConflict",  { fg = "#738490" })
      vim.api.nvim_set_hl(0, "NeoTreeGitModified",  { fg = "#738490" })
      vim.api.nvim_set_hl(0, "NeoTreeGitUntracked", { fg = "#738490" })
      vim.api.nvim_set_hl(0, "NeoTreeGitUnstaged",  { fg = "#738490" })
      vim.api.nvim_set_hl(0, "NeoTreeNormal", { bg = darker_black })
      vim.api.nvim_set_hl(0, "NeoTreeNormalNC",  { bg = darker_black })
      vim.api.nvim_set_hl(0, "NeoTreeNormal",    { bg = darker_black })
      vim.api.nvim_set_hl(0, "NeoTreeNormalNC",  { bg = darker_black })
    end,
  }


}
